version: "3.8"

services:
  server:
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
